version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: boilerplate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres-data: